more verbose

diff --git a/.github/workflows/mydebs-check.yml b/.github/workflows/mydebs-check.yml
--- a/.github/workflows/mydebs-check.yml
+++ b/.github/workflows/mydebs-check.yml
@@ -16,6 +16,9 @@ jobs:
           set -ex
           apt-get update -qq && apt-get install -y curl
       - name: network check
+        shell: bash
         run: |
+          set -ex
           echo "My IP address: $(curl -s ipinfo.io/ip)"; true
-          curl -v --connect-timeout 5 http://bbbike.de/robots.txt > /dev/null
+          { set -o pipefail; curl -s -I http://bbbike.de/robots.txt | head -1; } || { echo "::warning::network check on port 80 failed"; }
+          { set -o pipefail; curl -s -I http://mydebs.bbbike.de:8000/dists/jessie/InRelease | head -1; true; } || { echo "::warning::network check on port 8000 failed"; }
