new version of network_check:

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -125,35 +125,35 @@ jobs:
 #          #sudo apt-get install -y expect
 #          #unbuffer sh -c 'echo "before test"; stty -a; perl -Mblib -MDoit -e '\''my$sudo=Doit->init->do_sudo;$sudo->system("id");$sudo->system("id")'\''; echo "after test"; stty -a'
 
-  doit-single-test-mac:
-    name: doit-single-test-mac on ${{ matrix.os }}
-    runs-on: ${{ matrix.os }}
-    continue-on-error: true
-    strategy:
-      matrix:
-        include:
-#          - os: macos-13
-#          - os: macos-14
-          - os: macos-15
-    steps:
-      - run: |
-          echo "::group::install"
-          brew install pstree
-          git clone https://github.com/eserte/Doit.git
-          cd Doit
-          git checkout XXX-github-actions
-          perl Build.PL
-          perl Build
-          echo "::endgroup::"
-          #echo "::group::all locales"
-          #locale -a | sort
-          #echo "::endgroup::"
-          pid=$$; (sleep 20; pstree -pa $pid) &
-          #(sleep 21; ps auxgww) &
-          echo "DOIT_TRACE=1 DOIT_TEST_WITH_SUDO=1 prove -vb t/sudo.t"
-      - uses: mxschmitt/action-tmate@v3
-        with:
-          limit-access-to-actor: true
+#  doit-single-test-mac:
+#    name: doit-single-test-mac on ${{ matrix.os }}
+#    runs-on: ${{ matrix.os }}
+#    continue-on-error: true
+#    strategy:
+#      matrix:
+#        include:
+##          - os: macos-13
+##          - os: macos-14
+#          - os: macos-15
+#    steps:
+#      - run: |
+#          echo "::group::install"
+#          brew install pstree
+#          git clone https://github.com/eserte/Doit.git
+#          cd Doit
+#          git checkout XXX-github-actions
+#          perl Build.PL
+#          perl Build
+#          echo "::endgroup::"
+#          #echo "::group::all locales"
+#          #locale -a | sort
+#          #echo "::endgroup::"
+#          pid=$$; (sleep 20; pstree -pa $pid) &
+#          #(sleep 21; ps auxgww) &
+#          echo "DOIT_TRACE=1 DOIT_TEST_WITH_SUDO=1 prove -vb t/sudo.t"
+#      - uses: mxschmitt/action-tmate@v3
+#        with:
+#          limit-access-to-actor: true
 
 #  doit-windows:
 #    runs-on: windows-latest
@@ -194,22 +194,17 @@ jobs:
 #      with:
 #        limit-access-to-actor: true
 #
-#  network_check:
-#    if: true
-#    runs-on: ubuntu-latest
-#    steps:
-#    - run: |
-#        echo "My IP address: $(curl -s ipinfo.io/ip)"; true
-#        #curl --connect-timeout 5 https://www.bbbike.org/robots.txt > /dev/null
-#        echo Run again non-80 port using libwww-perl
-#        lwp-request -t 1 http://bbbike.de:8443/ || true
-#        sleep 1
-#        echo Run again non-80 port using curl
-#        timeout 5 curl -v --connect-timeout 5 http://bbbike.de:8443 > /dev/null || true
-#        echo Run again 80 port using libwww-perl
-#        HEAD -t 5 http://bbbike.de/robots.txt
-#        echo Run again 80 port using curl
-#        curl -v --connect-timeout 5 http://bbbike.de/robots.txt > /dev/null
+  network_check:
+    if: true
+    runs-on: ubuntu-latest
+    steps:
+    - run: |
+        set -ex
+        echo "My IP address: $(curl -s ipinfo.io/ip)"; true
+        { set -o pipefail; curl -s -I http://bbbike.de/robots.txt | head -1; } || { echo "::warning::network check on bbbike.de port 80 failed";            echo "BBBIKE_TEST_SKIP_BBBIKE_DE=1"  >> "$GITHUB_ENV"; }
+        { set -o pipefail; curl -s -I https://download.bbbike.org | head -1; } || { echo "::warning::network check on download.bbbike.org port 443 failed"; echo "BBBIKE_TEST_SKIP_BBBIKE_ORG=1" >> "$GITHUB_ENV"; }
+        { set -o pipefail; curl -s -I https://opendata.dwd.de | head -1; } || { echo "::warning::network check on opendata.dwd.de port 443 failed"; }
+        { set -o pipefail; curl -s -I http://mydebs.bbbike.de:8000/dists/jessie/InRelease | head -1; } || { echo "::warning::network check on port 8000 failed"; }
 #
 #  test_on_host:
 #    if: false
