try out checkout@v4 @ stretch

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,58 +11,65 @@ on:
 
 jobs:
 
-  zgrep-pipe-error:
-    if: true
+  checkout-v4:
     runs-on: ubuntu-latest
+    container: perl:5.22.4-stretch
     steps:
-    - uses: actions/checkout@v3
-    - run: |
-        ./pipefail.sh
-        wget -q https://www.cpan.org/modules/02packages.details.txt
-        gzip 02packages.details.txt
-        zgrep -q KARASIK/Prima-1.68001.tar.gz 02packages.details.txt.gz
+      # still fails (2023-10-24)
+      - uses: actions/checkout@v4
 
-  vm-info:
-    if: false
-    runs-on: ubuntu-latest
-    steps:
-    - run: |
-        cat /proc/sys/fs/pipe-max-size
-
-  github-env:
-    if: false
-    runs-on: ubuntu-latest
-    steps:
-    - run: |
-        mkdir -p ~/.cpan/sources/modules/
-        echo "bla KARASIK/Prima-1.68001.tar.gz foo" | gzip > ~/.cpan/sources/modules/02packages.details.txt.gz
-        echo "<<$GITHUB_ENV>>"
-        if zgrep -q KARASIK/Prima-1.68001.tar.gz ~/.cpan/sources/modules/02packages.details.txt.gz; then echo "SKIP_PRIMA=true" >> $GITHUB_ENV; fi
-    - run: |
-        echo "This should not run!"
-      if: "!env.SKIP_PRIMA"
-
-  conditional-cpan-build:
-    if: false
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v3
-      with:
-        repository: eserte/travis-helper-cpan-pm
-        #ref: master
-        path: travis-helper-cpan-pm
-    - name: before_install
-      run: |
-        $GITHUB_WORKSPACE/travis-helper-cpan-pm/travis-helper-cpan-pm --distroprefs=https://github.com/eserte/srezic-cpan-distroprefs --enable-sysdeps --sysdeps-branch=master
-    - name: check Prima version
-      run: |
-        ls -al ~/.cpan/sources/modules
-        echo "<<$GITHUB_ENV>>"
-        if zgrep -l KARASIK/Prima-1.68001.tar.gz ~/.cpan/sources/modules/02packages.details.txt.gz >/dev/null; then echo "SKIP_PRIMA=true" >> $GITHUB_ENV; fi
-    - name: install Prima
-      run: |
-        cpan Prima
-      if: "!env.SKIP_PRIMA"
+#  zgrep-pipe-error:
+#    if: true
+#    runs-on: ubuntu-latest
+#    steps:
+#    - uses: actions/checkout@v3
+#    - run: |
+#        ./pipefail.sh
+#        wget -q https://www.cpan.org/modules/02packages.details.txt
+#        gzip 02packages.details.txt
+#        zgrep -q KARASIK/Prima-1.68001.tar.gz 02packages.details.txt.gz
+#
+#  vm-info:
+#    if: false
+#    runs-on: ubuntu-latest
+#    steps:
+#    - run: |
+#        cat /proc/sys/fs/pipe-max-size
+#
+#  github-env:
+#    if: false
+#    runs-on: ubuntu-latest
+#    steps:
+#    - run: |
+#        mkdir -p ~/.cpan/sources/modules/
+#        echo "bla KARASIK/Prima-1.68001.tar.gz foo" | gzip > ~/.cpan/sources/modules/02packages.details.txt.gz
+#        echo "<<$GITHUB_ENV>>"
+#        if zgrep -q KARASIK/Prima-1.68001.tar.gz ~/.cpan/sources/modules/02packages.details.txt.gz; then echo "SKIP_PRIMA=true" >> $GITHUB_ENV; fi
+#    - run: |
+#        echo "This should not run!"
+#      if: "!env.SKIP_PRIMA"
+#
+#  conditional-cpan-build:
+#    if: false
+#    runs-on: ubuntu-latest
+#    steps:
+#    - uses: actions/checkout@v3
+#      with:
+#        repository: eserte/travis-helper-cpan-pm
+#        #ref: master
+#        path: travis-helper-cpan-pm
+#    - name: before_install
+#      run: |
+#        $GITHUB_WORKSPACE/travis-helper-cpan-pm/travis-helper-cpan-pm --distroprefs=https://github.com/eserte/srezic-cpan-distroprefs --enable-sysdeps --sysdeps-branch=master
+#    - name: check Prima version
+#      run: |
+#        ls -al ~/.cpan/sources/modules
+#        echo "<<$GITHUB_ENV>>"
+#        if zgrep -l KARASIK/Prima-1.68001.tar.gz ~/.cpan/sources/modules/02packages.details.txt.gz >/dev/null; then echo "SKIP_PRIMA=true" >> $GITHUB_ENV; fi
+#    - name: install Prima
+#      run: |
+#        cpan Prima
+#      if: "!env.SKIP_PRIMA"
 
 #  doit-windows:
 #    runs-on: windows-latest
